FROM node:18-alpine as build
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
# Skenario produksi menggunakan Nginx untuk melayani berkas statis build React
FROM nginx:alpine
COPY --from=build /app/public /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]